version: "3.4"

services:
  postgres:
    image: postgres:12.4
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
